# Release task for PbLib projects
# See https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema for reference
trigger:
  branches:
    include:
      - refs/tags/*

variables:
  - name: githubConnectionName
    value: releases
  - name: projectName
    value: lighthouse 
  - name: githubRepositoryName
    value: petabridge/lighthouse 
  - name: dockerConnectionName
    value: PetabridgeDocker

jobs:
  - job: publishNetCore
    pool:
      vmImage: windows-2019
      demands: Cmd
    steps:
    - task: BatchScript@1
      displayName: 'dotnet publish'
      inputs:
        filename: build.cmd
        arguments: 'PublishCode'
    - task: CopyFiles@2
      displayName: 'Copy dotnet publish Output'
      inputs:
        sourceFolder: src/Lighthouse/bin/Release/netcoreapp2.1/publish/
        targetFolder: $(Build.ArtifactStagingDirectory)/bin/Release/netcoreapp2.1/publish/
    - task: CopyFiles@2
      displayName: 'Copy Dockerfiles'
      inputs:
        sourceFolder: src/Lighthouse
        contents: Dockerfile-*
        targetFolder: $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: drop
    - task: GitHubRelease@0
      displayName: 'GitHub release (create)'
      inputs:
        gitHubConnection: $(githubConnectionName)
        repositoryName: $(githubRepositoryName)
        title: '$(projectName) v$(Build.SourceBranchName)'
        releaseNotesFile: 'RELEASE_NOTES.md'
        assets: |
         bin\nuget\*.nupkg

  - job:  linuxImageDeploy
    pool:
      vmImage: ubuntu-16.04
    dependsOn: publishNetCore
    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'drop'
          itemPattern: drop/**
          downloadPath: '$(Build.StagingDirectory)'
      - task: CopyFiles@2
        displayName: 'Copy into working directory'
        inputs:
          sourceFolder: $(Build.StagingDirectory)/drop
          targetFolder: $(Agent.BuildDirectory)
      - task: CmdLine@2
        displayName: "DEBUG: list contents"
        inputs:
          workingDirectory: $(Agent.BuildDirectory)
          script: ls
      - task: Docker@2
        displayName: "Login to Docker Hub"
        inputs:
          command: login
          containerRegistry: $(dockerConnectionName)
      - task: Docker@2
        displayName: Docker Build (Linux)
        inputs:
          command: build
          Dockerfile: $(Agent.BuildDirectory)/Dockerfile-linux
          repository: petabridge/lighthouse
          tags: |
            latest
            $(Build.SourceBranchName)
            $(Build.SourceBranchName)-linux
      - task: Docker@2
        displayName: Docker Push (Linux)
        inputs:
          command: push
          repository: petabridge/lighthouse
      - task: Docker@2
        displayName: Logout of Docker Hub
        inputs:
          command: logout
          containerRegistry: $(dockerConnectionName)

  - job:  windowsImageDeploy
    pool:
      vmImage: windows-2019
    dependsOn: publishNetCore
    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'drop'
          itemPattern: drop/**
          downloadPath: '$(Build.StagingDirectory)'
      - task: CopyFiles@2
        displayName: 'Copy into working directory'
        inputs:
          sourceFolder: $(Build.StagingDirectory)/drop
          targetFolder: $(Agent.BuildDirectory)
      - task: CmdLine@2
        displayName: "DEBUG: list contents"
        inputs:
          workingDirectory: $(Agent.BuildDirectory)
          script: dir
      - task: Docker@2
        displayName: "Login to Docker Hub"
        inputs:
          command: login
          containerRegistry: $(dockerConnectionName)
      - task: Docker@2
        displayName: Docker Build (Windows)
        inputs:
          command: build
          Dockerfile: $(Agent.BuildDirectory)/Dockerfile-windows
          repository: petabridge/lighthouse
          tags: |
            latest
            $(Build.SourceBranchName)
            $(Build.SourceBranchName)-nanoserver
      - task: Docker@2
        displayName: Docker Push (Windows)
        inputs:
          command: push
          repository: petabridge/lighthouse
      - task: Docker@2
        displayName: Logout of Docker Hub
        inputs:
          command: logout
          containerRegistry: $(dockerConnectionName)